### ISSUE TITLE
usage 

### ISSUE THREAD

**Issue by Alakazam03** [jjyr/sparse-merkle-tree#1]
Hi, thanks for the package. I want to use it to create a smt to store my struct. Please, can you provide an example of how to do that? I have added your crate.

**Comment by jjyr** [comment]
Hi, you can learn from the test for now, https://github.com/jjyr/sparse-merkle-tree/blob/master/src/lib.rs#L285

Hash your struct into [u8;32], then update the position in SMT.

As u can see, this crate is still in experiment, I am not satify the gernalization ability. I'll make more exaplems after the crate becoming more stable.

**Comment by Alakazam03** [comment]
Hi, thanks for the reply! I figured that out, thank you for the package. 
I am still new to development. I want to use a global static Merkle tree so that I can access the singleton across my different APIs.
I tried using lazy_static and rocket crate's managing state. But I a getting error because of send is not implemented and thread can not be shared safely.
I have already tried using so many packages also. Please can you help?
![image](https://user-images.githubusercontent.com/23367724/66366531-620b4d80-e9ae-11e9-960e-c6d7e7425e76.png)
![image](https://user-images.githubusercontent.com/23367724/66366570-82d3a300-e9ae-11e9-8c66-f947f03a7201.png)
@jjyr

**Comment by jjyr** [comment]
I can't figure the problem from the snapshots. 

But I'd not recommend using this crate under the `lazy_static`, you can pass the struct as an argument.

**Comment by Alakazam03** [comment]
Sorry. I tried using lazy_static!
`
// lazy_static! {
//     static ref TREE : Mutex<SMT> =  Mutex::new(SMT::new(vec![0x42 as u8], digest_adapter(&digest::SHA256)));
// }

pub fn digest_adapter(algorithm: &'static digest::Algorithm) -> Box<Fn(&[u8])->Vec<u8>> {
    let closure = move |x:&[u8]|  digest::digest(algorithm, x).as_ref().to_vec();
    return Box::new(closure);
}

struct Tree {
    smt_tree : SMT,
}

fn main() {
    println!("Starting filtering service..");
    // sparse merkle tree
    let tree = Tree { smt_tree : SMT::new(vec![0x42 as u8], digest_adapter(&digest::SHA256))};
    let smt = SMT::new(vec![0x42 as u8], digest_adapter(&digest::SHA256));
    let mut key: Vec<Vec<u8>>= Vec::new();
    key.push((*digest_adapter(&digest::SHA256))(&"abc".as_bytes().to_vec()));

    let keys = Key::from_vec(key.clone());
    let prometheus = PrometheusMetrics::new();
    rocket::ignite()
        .manage(Mutex::new(tree))
        .attach(prometheus.clone())
        .mount("/metrics", prometheus)
        .launch();
}
`

On running this I am getting an error in the image above. Sorry for taking your time

**Comment by jjyr** [comment]
What is `SMT` struct? The compile tells you can't pass a `dyn fn` across the thread, so IMO this error is not related to `sparse-merkle-tree` crate.
